// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_kD9yJuyxWC9P7xWduG2gxjdcGdIvlZo',
    appId: '1:603861569604:web:01dde6edc021ee86b42c11',
    messagingSenderId: '603861569604',
    projectId: 'dothithongminh-1f8d6',
    authDomain: 'dothithongminh-1f8d6.firebaseapp.com',
    storageBucket: 'dothithongminh-1f8d6.appspot.com',
    measurementId: 'G-E2E6JRBZNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Kzw6cZYYSZoMA_3DIi6_Ux1aDH_98sE',
    appId: '1:603861569604:android:4f4a9a16aac268cab42c11',
    messagingSenderId: '603861569604',
    projectId: 'dothithongminh-1f8d6',
    storageBucket: 'dothithongminh-1f8d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9xYqVJYWZvdSuqMTYTDcZ9Y2sxEuZjKc',
    appId: '1:603861569604:ios:dca9bc638fd760d4b42c11',
    messagingSenderId: '603861569604',
    projectId: 'dothithongminh-1f8d6',
    storageBucket: 'dothithongminh-1f8d6.appspot.com',
    iosBundleId: 'n.quang.doThiThongMinh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9xYqVJYWZvdSuqMTYTDcZ9Y2sxEuZjKc',
    appId: '1:603861569604:ios:5620e2c8d8d460ecb42c11',
    messagingSenderId: '603861569604',
    projectId: 'dothithongminh-1f8d6',
    storageBucket: 'dothithongminh-1f8d6.appspot.com',
    iosBundleId: 'n.quang.doThiThongMinh.RunnerTests',
  );
}
